### ISSUE TITLE
adding the addpack to regular openwrt  repo and compiling

### ISSUE THREAD

**Issue by silent-mobius** [tobiaswaldvogel/openwrt-addpack#9]
Hi,
 sorry for newby question: if i want to add your pack to regular openwrt repo and then compile it with "make menuconfig" ,  i just need to clone it to  openwrt folder?
thanks in advance.

**Comment by Wedmer** [comment]
http://wiki.openwrt.org/doc/devel/feeds

**Comment by silent-mobius** [comment]
thanks Wedmer
appreciate it very much.
